"""CAP-005 Risk -- Risk Control (Etapa 4.5, M4.5-T1, 2026-09-29): quantitative
pre-execution limits applied OVER decisions already generated by M1.1,
without touching signal generation (DOC-002 §3.1: strict strategy/risk
separation).

This is the quantitative Risk Engine DOC-011 §6 said was still missing:
today only "Risk PAPER" (state-transition authority) exists, plus a
hardcoded proposal check in pipeline.py's `prepare_real_order_proposal`
that is wired to literals (max_capital==200, exposure<=50, budget==5),
one strategy (SMA3_LONG_ONLY), one broker (Alpaca), and -- critically --
carries only the exposure limit (RL-008-002), never the drawdown limit
(RL-008-001).

Risk Control produces exactly the M3.1 operational vocabulary:
  COMPLETED -- the proposed action operates within every declared limit.
  BLOCKED   -- at least one limit is exceeded; the breached limits are named.
It never approves, sizes, or executes; it only gates. Execution belongs to
the Broker Adapter (M4.5-T2); the multi-evaluation decision belongs to the
Investment Committee (M4.5-T3). Risk Control is one input to IC-2 (Riesgo).

Reuse (per the Director's requirement that prior work serve future stages):
the drawdown limit RL-008-001 applies the SAME peak-to-trough metric that
M2.6-T4 Risk Analytics (`_risk_analytics_max_drawdown` in walk_forward.py)
reports descriptively. Analytics describes a strategy's historical risk;
Control gates a live one against a declared ceiling. Same computation, two
uses. It is reimplemented here (not imported) to keep this capability free
of a research/ dependency; the lineage is documented, and a shared-helper
extraction is a separate, optional cleanup.

Deliberately parametric: the limits live in a declared `risk_contract`, not
in literals. That is the whole point -- Governance must be able to authorize
a genuinely different configuration, which the hardcoded pipeline.py version
forbids. Migrating M1.x to call this module instead of its literal checks is
a later, deliberate microciclo, flagged, not done here.
"""

from decimal import Decimal, InvalidOperation

RISK_CONTROL_SCHEMA_VERSION = "1"
RISK_CONTROL_COMPLETED = "COMPLETED"
RISK_CONTROL_BLOCKED = "BLOCKED"

# The two limits DOC-008 RL-008-001/002 name, and only these -- Risk Control
# is minimal by design (M4.5-T1). Named so a breach report is unambiguous.
RISK_LIMIT_TOTAL_EXPOSURE = "RL-008-002-total-exposure"
RISK_LIMIT_MAX_DRAWDOWN = "RL-008-001-max-drawdown"


def _risk_decimal(value, field):
    """Money is Decimal, matching pipeline.py's proposal arithmetic. Accepts a
    string or int (never a float, whose representation error has no place in a
    risk limit)."""
    if isinstance(value, bool) or not isinstance(value, (str, int)):
        raise ValueError(field + " must be a string or integer amount")
    try:
        amount = Decimal(value)
    except InvalidOperation as error:
        raise ValueError(field + " is not a valid decimal amount") from error
    if not amount.is_finite():
        raise ValueError(field + " must be finite")
    return amount


def risk_contract(*, max_total_exposure_usd, max_drawdown_ratio):
    """A declared, parametric set of limits -- NOT literals baked into code.

    max_total_exposure_usd : the ceiling on open notional (RL-008-002), a
                             positive decimal amount.
    max_drawdown_ratio     : the ceiling on peak-to-trough equity decline
                             (RL-008-001), a float in (0, 1].
    """
    exposure = _risk_decimal(max_total_exposure_usd, "max_total_exposure_usd")
    if exposure <= 0:
        raise ValueError("max_total_exposure_usd must be positive")
    if (isinstance(max_drawdown_ratio, bool)
            or not isinstance(max_drawdown_ratio, (int, float))
            or not 0 < float(max_drawdown_ratio) <= 1):
        raise ValueError("max_drawdown_ratio must be a number in (0, 1]")
    return {
        "schema_version": RISK_CONTROL_SCHEMA_VERSION,
        "max_total_exposure_usd": str(exposure),
        "max_drawdown_ratio": float(max_drawdown_ratio),
    }


def _equity_max_drawdown(equity_curve):
    """Maximum peak-to-trough decline of a realized equity series. Same metric
    as M2.6-T4's _risk_analytics_max_drawdown, computed here directly from
    portfolio values rather than from returns. 0.0 for an empty or
    never-declining curve."""
    peak = None
    max_drawdown = 0.0
    for value in equity_curve:
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise ValueError("Equity curve values must be numbers")
        v = float(value)
        peak = v if peak is None else max(peak, v)
        if peak > 0:
            max_drawdown = max(max_drawdown, (peak - v) / peak)
    return max_drawdown


def evaluate_risk_control(*, contract, proposed_total_exposure_usd, equity_curve):
    """Gate one proposed action against every declared limit.

    proposed_total_exposure_usd : the open notional AFTER the proposed action
                                  (the position the action would leave standing).
    equity_curve                : the realized portfolio-value history up to
                                  now (list of numbers), used for the drawdown
                                  limit. An empty history has zero drawdown.

    Returns a result carrying COMPLETED or BLOCKED and, when BLOCKED, the exact
    limits breached with their observed vs allowed values. Never sizes or
    approves -- a COMPLETED result is a permission to proceed, not an order."""
    if (not isinstance(contract, dict)
            or contract.get("schema_version") != RISK_CONTROL_SCHEMA_VERSION):
        raise ValueError("A valid risk contract is required")
    max_exposure = _risk_decimal(contract["max_total_exposure_usd"], "max_total_exposure_usd")
    max_drawdown = contract["max_drawdown_ratio"]
    proposed = _risk_decimal(proposed_total_exposure_usd, "proposed_total_exposure_usd")
    if proposed < 0:
        raise ValueError("proposed_total_exposure_usd must not be negative")
    observed_drawdown = _equity_max_drawdown(equity_curve)

    breaches = []
    if proposed > max_exposure:
        breaches.append({
            "limit": RISK_LIMIT_TOTAL_EXPOSURE,
            "observed": str(proposed), "allowed": str(max_exposure)})
    if observed_drawdown > max_drawdown:
        breaches.append({
            "limit": RISK_LIMIT_MAX_DRAWDOWN,
            "observed": observed_drawdown, "allowed": max_drawdown})

    return {
        "schema_version": RISK_CONTROL_SCHEMA_VERSION,
        "outcome": RISK_CONTROL_BLOCKED if breaches else RISK_CONTROL_COMPLETED,
        "evaluated": {
            "proposed_total_exposure_usd": str(proposed),
            "observed_max_drawdown_ratio": observed_drawdown,
        },
        "limits": {
            "max_total_exposure_usd": str(max_exposure),
            "max_drawdown_ratio": max_drawdown,
        },
        "breaches": breaches,
    }
